[tool.isort]
profile = "black"

[tool.mypy]
strict = true
follow_imports = "silent"
allow_redefinition = false
disallow_any_unimported = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_context = true
show_column_numbers = true
pretty = true
html_report = ".reports/mypy_html"
xml_report = ".reports/mypy_xml"
junit_xml = ".reports/mypy_junit.xml"
python_version = "3.7"
strict_optional = true
warn_unused_ignores = true

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bank-widget-project"
version = "0.1.0"
description = ""
authors = ["Your Name"]  # Ваше имя
license = "MIT"
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2"
flake8 = "^3.9"
black = "^22.3"
isort = "^5.10"
mypy = "^0.930"

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
  \.eggs
| \.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
| dist
)/'''